#!/usr/bin/env ruby
# require 'bundler'
# Bundler.require

require "bunny"
require "thread"
require "json"

queue_name = ARGV.shift
json_data = ARGV.shift

json_data ||= "{}"

fail "Usage: #$0 <queue-name> [<json-data>]" unless queue_name
begin
  JSON.parse(json_data)
rescue 
  fail "Pass correct json as <json-data> attribute - was #{json_data}."
end


#!/usr/bin/env ruby
# encoding: utf-8

host = ENV["RABBIT_HOST"] || 'localhost'
port = ENV["RABBIT_PORT"] || 5672
user = ENV["RABBIT_USER"] || 'guest'
password = ENV["RABBIT_PASSWORD"] || 'guest'

conn = Bunny.new("amqp://#{user}:#{password}@#{host}:#{port}")
conn.start

ch = conn.create_channel

class MQClient
  attr_reader :reply_queue
  attr_accessor :response, :call_id
  attr_reader :lock, :condition

  def initialize(ch, server_queue)
    @ch             = ch
    @x              = ch.default_exchange

    @server_queue   = server_queue
    @reply_queue    = ch.queue("", :exclusive => true)


    @lock      = Mutex.new
    @condition = ConditionVariable.new
    that       = self

    @reply_queue.subscribe do |delivery_info, properties, payload|
      if properties[:correlation_id] == that.call_id
        that.response = payload
        that.lock.synchronize{that.condition.signal}
      end
    end
  end

  def call(request)
    self.call_id = self.generate_uuid

    @x.publish(request.to_s,
      :routing_key    => @server_queue,
      :correlation_id => call_id,
      :reply_to       => @reply_queue.name)

    lock.synchronize{condition.wait(lock)}
    response
  end

  protected

  def generate_uuid
    # very naive but good enough for code
    # examples
    "#{rand}#{rand}#{rand}"
  end
end


client   = MQClient.new(ch, queue_name)
response = client.call(json_data)
puts response
ch.close
conn.close