#!/usr/bin/env ruby
require 'bundler'
Bundler.require

require_relative '../providers/clients'
require_relative '../providers/invoices'

host = ENV["RABBIT_HOST"] || 'localhost'
port = ENV["RABBIT_PORT"] || 5672
user = ENV["RABBIT_USER"] || 'guest'
password = ENV["RABBIT_PASSWORD"] || 'guest'

puts "Starting up service..."
sleep 5 # give rabbitmq time to get up

conn = Bunny.new("amqp://#{user}:#{password}@#{host}:#{port}")
conn.start
conn.start

begin

  ch1 = conn.create_channel
  ch2 = conn.create_channel
  Thread.new{ Providers::Clients.new(ch1).start  } 
  Thread.new{ Providers::Invoices.new(ch2).start  } 

  puts " [x] Awaiting RPC requests"
  sleep 
  
rescue Interrupt => _
  ch1.close
  ch2.close
  conn.close

  exit(0)
end